const loremIpsum = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper ac ante quis pretium. Sed id bibendum odio, vitae vehicula dui. Aenean fringilla sapien sed metus dapibus, sit amet consequat dolor laoreet. Pellentesque est mi, tincidunt sed gravida ac, commodo non mi. Vivamus et tincidunt massa. Vestibulum mattis risus nec arcu varius consectetur. Vestibulum pulvinar ipsum non ex viverra laoreet. Vestibulum vestibulum mollis elit eu ullamcorper. In eget tincidunt lectus. Nunc maximus bibendum egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum vel mi at velit dignissim pharetra eu non justo. Fusce eu lorem erat. Aliquam quis aliquet massa, semper ultricies nibh. Phasellus feugiat dictum dignissim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Ut bibendum eget felis at auctor. Nam sodales dignissim est ut semper. Morbi ultrices enim id mauris interdum tincidunt. Donec vehicula laoreet ipsum sed congue. Curabitur semper felis tortor, et cursus tortor accumsan eu. Aliquam elementum fringilla tellus sed ullamcorper. In sit amet finibus lorem. Nulla facilisi. In nec eleifend purus. Aliquam erat volutpat. Mauris nunc ipsum, vulputate at vulputate non, feugiat sed nibh. Vivamus id vestibulum lacus. Curabitur tempor tincidunt scelerisque.

Sed dignissim libero dolor, sed fringilla orci posuere in. Duis eget rhoncus mauris, at mollis risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In auctor congue sodales. Morbi aliquam tortor et magna tincidunt, vitae gravida mauris ultricies. Integer in lectus vulputate, commodo tellus vel, blandit justo. Phasellus in interdum lectus. Sed efficitur dui et euismod aliquam.

Ut consequat tortor vulputate, iaculis ante vel, volutpat lorem. Suspendisse potenti. Donec a lectus porttitor, tincidunt est vel, vestibulum purus. Suspendisse mauris justo, vestibulum ac efficitur eget, eleifend sed nunc. Donec iaculis placerat neque vitae vulputate. Pellentesque auctor, lectus quis euismod ultrices, diam purus fringilla enim, et rutrum lorem lorem ut massa. Cras ut fermentum mi, nec blandit erat. Sed varius orci purus, id facilisis augue tempus at. Nulla sed nisi consectetur, facilisis augue eu, commodo diam. Mauris sed neque et quam pulvinar faucibus. Vestibulum dapibus sagittis sodales. Suspendisse orci purus, pulvinar vitae molestie porttitor, ultrices a enim.

Suspendisse sodales lorem felis, commodo imperdiet quam congue non. Mauris euismod eget lectus nec blandit. Integer condimentum sit amet eros a luctus. Integer ultricies nisl non interdum malesuada. Sed ac nulla imperdiet justo consequat lobortis et vel neque. Ut eu leo ac nunc eleifend tempus. Duis id sem sit amet quam fringilla tristique. Vivamus a diam nibh. Vivamus et lobortis tellus. Nam non orci libero. Curabitur libero felis, commodo ac neque sit amet, efficitur auctor orci.

Suspendisse elementum risus non interdum varius. Vivamus volutpat mauris vitae egestas convallis. Integer id justo nec eros mattis rutrum. Donec at hendrerit tortor. Ut accumsan nisl eget risus faucibus, nec sodales arcu scelerisque. Donec at pulvinar turpis. Nunc vitae tempor libero. Praesent ornare accumsan egestas.

Donec feugiat urna sapien, efficitur mattis metus hendrerit non. Suspendisse vitae egestas enim. Etiam lobortis auctor leo. Etiam semper ornare fringilla. Nulla malesuada, nisi nec mattis tincidunt, ipsum felis commodo lorem, at fermentum velit augue sed urna. Sed vestibulum magna in ligula porta ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam eget sapien fermentum, maximus odio ac, lobortis dolor. Mauris nisi metus, pulvinar ut lacinia ac, finibus nec est. Fusce vehicula sed nunc ac viverra. Pellentesque pulvinar quis orci vel mollis. Cras viverra leo nec urna eleifend finibus. Aliquam tempus orci et ex vehicula bibendum. Donec vel eleifend diam.

In finibus tortor vitae lacus efficitur, ac convallis arcu ultrices. Quisque iaculis, mauris at malesuada vestibulum, sem justo convallis odio, eget eleifend enim nisi et mauris. Curabitur viverra lobortis eros. Aenean sed turpis at arcu ultricies tincidunt a nec elit. Vivamus egestas malesuada ipsum sodales malesuada. Ut tincidunt vel ante tincidunt vulputate. Donec pharetra sed sem quis interdum. Nulla finibus malesuada nunc sed varius. In ut pellentesque nulla, vitae congue metus. Cras sagittis, quam eget tempus vulputate, libero tellus viverra justo, a vulputate velit libero eu lectus. Vivamus et rhoncus massa. Aliquam tristique turpis nec sem blandit suscipit. Vestibulum sed velit quis sapien luctus scelerisque eu sed velit.

Vestibulum maximus neque at quam hendrerit tincidunt. Ut sodales justo eu enim volutpat elementum. Cras dapibus vitae leo auctor condimentum. Aenean ultrices ipsum et porta eleifend. Integer a turpis vel leo blandit rhoncus id eu purus. Pellentesque blandit, elit in ullamcorper consectetur, tortor dolor sodales elit, sed hendrerit orci nibh vitae lorem. Sed a varius mi. Maecenas imperdiet, neque id tristique sodales, lorem nisi aliquam magna, non lobortis mauris nisl id elit. Aenean finibus elementum cursus.

Duis vel nunc auctor, faucibus erat in, porta elit. Ut consequat eros enim, nec luctus tortor lobortis sed. Aenean sed blandit felis. Proin ac nunc vel turpis venenatis tincidunt. Sed ut sapien leo. Duis augue nulla, volutpat eu auctor at, ultricies eget elit. Proin nulla nisl, efficitur quis urna scelerisque, interdum egestas nunc. Aliquam vestibulum mauris a placerat ultricies. Nullam feugiat egestas aliquet. Sed et lacinia sapien. In pharetra sem vel velit ultrices, in malesuada mauris pretium. Ut nisl metus, consectetur vel dui nec, viverra blandit magna. In volutpat quam eu felis venenatis, vel tincidunt libero suscipit. In sagittis eros eu sapien ultrices congue.
`;

export default loremIpsum;
